name = "QRupdate"
uuid = "29d2ae51-7246-454b-9a65-19ff7b2849a5"
authors = ["mleprovost <mathow@g.ucla.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
